query_sync:
  url: http://127.0.0.1:8001/
  interval: 5
metricsNameSnakeCase: true
domainQualifier: true
restPort: 7001
queries:
  - key: name
    keyName: server
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        type: WebAppComponentRuntime
        prefix: webapp_config_
        key: name
        values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
        servlets:
          prefix: weblogic_servlet_
          key: servletName
          values: invocationTotalCount
  - JVMRuntime:
      prefix: wls_jvm_
      key: name
      values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime]
  - executeQueueRuntimes:
      prefix: wls_socketmuxer_
      key: name
      values: [pendingRequestCurrentCount]
  - workManagerRuntimes:
      prefix: wls_workmanager_
      key: name
      values: [stuckThreadCount, pendingRequests, completedRequests]
  - threadPoolRuntime:
      prefix: wls_threadpool_
      key: name
      values: [executeThreadTotalCount, queueLength, stuckThreadCount, hoggingThreadCount]
  - JMSRuntime:
      key: name
      keyName: jmsruntime
      prefix: wls_jmsruntime_
      JMSServers:
        prefix: wls_jms_
        key: name
        keyName: jmsserver
        destinations:
          prefix: wls_jms_dest_
          key: name
          keyName: destination
  - persistentStoreRuntimes:
      prefix: wls_persistentstore_
      key: name
  - TARuntime:
      prefix: wls_jta_
      key: name